production:
  sessions:
    default:
      <% 
      default_config = { :host_port => 'localhost:27017', :user => 'openshift', :password => 'mooo', :db => 'openshift_broker' } 
      config = defined?(Rails) ? Rails.application.config.datastore : default_config
      %>
      database: <%= config[:db] %>
      hosts:
        <% config[:host_port].split(',').each do |server| %>
        - <%= server %>
        <% end %>
      <% if config[:user] %>
      username: "<%= config[:user] %>"
      <% end 
         if config[:password]
      %>
      password: "<%= config[:password] %>"
      <% end %>
      options:
        consistency: :strong
        safe: true
        ssl: <%= config[:ssl] %>
        write:
          w: <%= config[:write_replicas] %>
  options:
    raise_not_found_error: true
    include_type_for_serialization: true
development:
  sessions:
    default:
      <% 
      default_config = { :host_port => 'localhost:27017', :user => 'openshift', :password => 'mooo', :db => 'openshift_broker_dev' } 
      config = defined?(Rails) ? Rails.application.config.datastore : default_config
      %>
      database: <%= config[:db] %>
      hosts:
        <% config[:host_port].split(',').each do |server| %>
        - <%= server %>
        <% end %>
      <% if config[:user] %>
      username: "<%= config[:user] %>"
      <% end 
         if config[:password]
      %>
      password: "<%= config[:password] %>"
      <% end %>
      options:
        consistency: :strong
        safe: true
        ssl: <%= config[:ssl] %>
        write:
          w: <%= config[:write_replicas] %>
  options:
    raise_not_found_error: true
    include_type_for_serialization: true
test:
  sessions:
    default:
      <% 
      default_config = { :host_port => 'localhost:27017', :user => 'openshift', :password => 'mooo', :db => 'openshift_broker_test' } 
      config = defined?(Rails) ? Rails.application.config.datastore : default_config
      %>
      database: <%= config[:db] %>
      hosts:
        <% config[:host_port].split(',').each do |server| %>
        - <%= server %>
        <% end %>
      username: "<%= config[:user] %>"
      password: "<%= config[:password] %>"
      options:
        consistency: :strong
        safe: true
        ssl: <%= config[:ssl] %>
        write:
          w: <%= config[:write_replicas] %>
  options:
    raise_not_found_error: true
    include_type_for_serialization: true
