development:
  sessions:
    default:
      database: openshift_broker_dev
      hosts:
        - localhost:27017
      username: openshift
      password: mooo
      options:
        ssl: false
production:
  sessions:
    default:
      database: openshift_broker_dev
      hosts:
        - localhost:27017
      username: openshift
      password: mooo
      options:
        ssl: false
test:
  sessions:
    default:
      database: openshift_broker_dev
      hosts:
        - localhost:27017
      username: openshift
      password: mooo
      options:
        ssl: false
