development:
  sessions:
    default:
      database: openshift_broker_dev
      hosts:
        - localhost:27017
      username: openshift
      password: mooo
  options:
    ssl: false
    raise_not_found_error: true
production:
  sessions:
    default:
      database: openshift_broker
      hosts:
        - localhost:27017
      username: openshift
      password: mooo
  options:
    ssl: false
    raise_not_found_error: true
test:
  sessions:
    default:
      database: openshift_broker_dev
      hosts:
        - localhost:27017
      username: openshift
      password: mooo
  options:
    ssl: false
    raise_not_found_error: true
